services:
  #Backend Server
  backend:
    image: community-platform-api
    build:
      context: .
      dockerfile: Large_Scale CommunityPlatform/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql; Port=3306;Database=MyDb;Uid=root;Pwd=${DB_ROOT_PASSWORD};
      - JwtSettings__Secret=${PROD_JWT_SECRET}
      - RedisOption__Configuration=redis
    depends_on:
      mysql:
        condition: service_healthy
  #MySQL
  mysql:
    image: mysql:8.0
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: MyDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
        
  #Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      
volumes:
  mysql_data:
    